# Generated by Django 5.1.15 on 2026-07-13 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.property'),
        ),
        migrations.AddField(
            model_name='room',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'area'], name='properties_city_f38e71_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'gender'], name='properties_propert_ce0b85_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['rent_min', 'rent_max'], name='properties_rent_mi_9c8661_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['avg_rating'], name='properties_avg_rat_5d7911_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_verified', 'is_active'], name='properties_is_veri_918385_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-created_at'], name='properties_created_2ede73_idx'),
        ),
    ]
